### ISSUE TITLE
License files not found for aspect-rs

### ISSUE THREAD

**Issue by pcd1193182** [sstadick/cargo-bundle-licenses#7]
Hello, I was testing out this tool, and I noticed that the license files were not found for the `aspect` or `aspect-weave` crates. The problem is that both crates are in the same repository, as subdirectories. The LICENSE files are located at the top level. I'm not sure if there's an easy way to resolve this issue, but I figured I would file it.

**Comment by sstadick** [comment]
Thanks for making the issue! You're right, this is a known issue that relies more on the other crates maintainers including / placing LICENSE files in expected areas.

I'm going to leave this open for now as it is something that needs dealing with at some point in time 👍
