### ISSUE TITLE
Removing/ignoring CARGO_HOME prefix?

### ISSUE THREAD

**Issue by morrisonlevi** [sstadick/cargo-bundle-licenses#8]
I'm using cargo-bundle-license in my CI to alert me when licenses have changed. However, the license file checker is sensitive to the `$CARGO_HOME` variable, so if I commit the license bundle on one system (my local machine) and check for compliance on another (the CI machines), then I'm likely to get nonsense messages, like this:

> [2022-03-16T13:17:41Z ERROR bundle_licenses_lib::bundle] Previous ring:0.16.20 does not match new ring:0.16.20

All that's different is license file path e.g.

```diff
-    license: License specified in file (/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/LICENSE)
+    license: License specified in file (/go/src/github.com/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/LICENSE)
```

As far as I can tell, this isn't a useful thing. Maybe something like `$CARGO_HOME/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/LICENSE` can be stored instead, with the variable _not_ expanded?

**Comment by sstadick** [comment]
The one-week turnaround obviously didn't happen! This will still make it in a release and is a good idea. If someone gets a PR in before me that would be awesome 👍

**Comment by sstadick** [comment]
@Skgland @morrisonlevi see v1.0.0 release

**Comment by sstadick** [comment]
I was overconfident in my CI - see v1.0.1
